### ISSUE TITLE
can't locate platform_detection and tracking

### ISSUE THREAD

**Issue by wbzhang233** [pablorpalafox/uav-autonomous-landing#3]
I catkin_make this project successfully,I built uav_vision absolutely,it like this:
`shell
[ 95%] Built target hector_gazebo_ros_baro
[ 96%] Built target cv_bridge_boost
[ 96%] Built target takeoff_generate_messages
[ 97%] Built target robot_state_broadcaster
[ 98%] Built target predict_filter
[100%] Built target ped_traj_pred
[100%] Linking CXX executable platform_detection
[100%] Built target platform_detection
[100%] Linking CXX executable platform_tracking
[100%] Built target platform_tracking
`
After source devel/setup.bash,I roslaunch detection_tracking.launch.I got 
`setting /run_id to 32550588-5af9-11ea-9a7b-000c2950a848
process[rosout-1]: started with pid [70312]
started core service [/rosout]
ERROR: cannot launch node of type [uav_vision/platform_detection]: can't locate node [platform_detection] in package [uav_vision]
ERROR: cannot launch node of type [uav_vision/platform_tracking]: can't locate node [platform_tracking] in package [uav_vision]
`
I don't know why.How can I use this repo without a joystick?

**Comment by pablopalafox** [comment]
Hey @wbzhang233! Thanks for finding this issue. With respect to the first problem, please check #2. With respect to not having a joystick, in theory it shouldn't be too difficult to control everything from the keyboard. I might add this functionality in the future, but it'd be awesome if you finally decide to implement it and contribute it to the repo. Thanks! I'll close the issue for now, since we can further discuss stuff about the previous issue in #2.
